### ISSUE TITLE
Highlight words

### ISSUE THREAD

**Issue by gustafl** [gustafl/lexeme#8]
Words already mapped should be highlighted in the text. I can't think of any other way than using a span for each highlighted word. Perhaps each lexical category should have its own color? Use border radius on the highlight to separate selections from each other. Design and implement the hightlight.

**Comment by gustafl** [comment]
Finished design:

``` html
<p><span class="determiner">L</span>'<span class="noun">année</span> 1866 ...
```

``` css
article span {
    border-radius: 5px;
    cursor: pointer;
}
```
